version: '3.8'

services:
  cleanup:
    image: postgres:15
    container_name: imuad_callisto_cleanup
    command: >
      sh -c '
      if [ "${RESET_DB}" = "true" ]; then
        echo "RESET_DB is true. Cleaning up db_data...";
        find /var/lib/postgresql/data -mindepth 1 -delete;
        chmod 700 /var/lib/postgresql/data;
      else
        echo "RESET_DB is false. Skipping cleanup.";
      fi'
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      RESET_DB: "${RESET_DB:-false}"

  db:
    image: postgres:15
    container_name: imuad_callisto_db
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      UID: "${UID:-1001}"
      GID: "${GID:-1001}"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    depends_on:
      cleanup:
        condition: service_completed_successfully

  setup:
    image: postgres:15
    container_name: imuad_callisto_db_setup
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./database/schema:/schema
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      BDJUNO_USER: "${BDJUNO_USER}"
      BDJUNO_PASSWORD: "${BDJUNO_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      UID: "${UID:-1001}"
      GID: "${GID:-1001}"
      RESET_DB: "${RESET_DB:-false}"
    entrypoint: ["/bin/bash", "/schema/setup-entrypoint.sh"]

  callisto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imuad_callisto_parser
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - ./callisto-config:/callisto/.callisto
    depends_on:
      setup:
        condition: service_completed_successfully

  hasura:
    image: hasura/graphql-engine:v2.37.0
    container_name: imuad_callisto_hasura
    ports:
      - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${BDJUNO_USER}:${BDJUNO_PASSWORD}@db:5432/bdjuno
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${BDJUNO_USER}:${BDJUNO_PASSWORD}@db:5432/bdjuno
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_ADMIN_SECRET:-yourSuperSecureAdminSecret}"
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura/migrations
      HASURA_GRAPHQL_METADATA_DIR: /hasura/metadata
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      ACTION_BASE_URL: "http://callisto:3000"
    volumes:
      - ./hasura:/hasura
    depends_on:
      setup:
        condition: service_completed_successfully

  hasura-cli:
    image: ubuntu:22.04
    container_name: imuad_callisto_hasura_cli
    volumes:
      - ./hasura:/hasura
    environment:
      HASURA_GRAPHQL_ENDPOINT: http://hasura:8080
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_ADMIN_SECRET:-yourSuperSecureAdminSecret}"
      RESET_METADATA: "${RESET_METADATA:-false}"
    depends_on:
      - hasura
    entrypoint: ["/bin/bash", "/hasura/metadata-entrypoint.sh"]
